#!/bin/bash
org="solinea"

echo "Building docker images..."

for dir in ./Dockerfiles/*
do
  pushd $dir &> /dev/null
    appname=`basename $dir`

    docker build -t ${org}/${appname}:latest
  popd &> /dev/null
done